apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2022-radix-app-dotnet-core-example
spec:
  environments:
    - name: dev
      build:
        from: main
  build:
    secrets:
      - CONNECTION_STRING
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        ASPNETCORE_URLS: "http://+:8000"
      secrets:
        - CONNECTION_STRING
